# Generated by Django 5.0 on 2024-01-21 21:02

import django.core.validators
import django.db.models.deletion
import dream.models
import phone_field.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Donate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0.01)]
                    ),
                ),
                ("currency", models.CharField(default="UAH", max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name="Dream",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(max_length=500)),
                (
                    "dream_type",
                    models.CharField(
                        choices=[
                            ("to-have", "To-Have"),
                            ("to-meet", "To-Meet"),
                            ("to-go", "To-Go"),
                            ("to-be", "To-Be"),
                        ],
                        max_length=20,
                    ),
                ),
                ("user_name", models.CharField(blank=True, max_length=255, null=True)),
                ("user_age", models.IntegerField()),
                (
                    "user_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "user_type",
                    models.CharField(
                        choices=[
                            ("requestor", "Dream Requestor"),
                            ("executor", "Dream Executor"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date", models.DateField()),
                (
                    "price",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                (
                    "attachment",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=dream.models.dream_image_file_path,
                    ),
                ),
                ("city", models.CharField(max_length=255)),
                ("region", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unfulfilled", "Unfulfilled"),
                            ("fulfilled", "Fulfilled"),
                            ("reserved", "Reserved"),
                        ],
                        default="unfulfilled",
                        max_length=255,
                    ),
                ),
                ("is_activated", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Benefactor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                (
                    "phone_number",
                    phone_field.models.PhoneField(
                        blank=True, help_text="Contact phone number", max_length=31
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "method_of_receipt",
                    models.CharField(
                        choices=[
                            ("personally", "Personally"),
                            ("indirectly", "Indirect"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "date_execution",
                    models.DateTimeField(
                        validators=[dream.models.not_past_date_validator]
                    ),
                ),
                (
                    "dream",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="benefactors",
                        to="dream.dream",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.FloatField()),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("success", models.BooleanField(default=None)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "dream",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="dream.dream",
                    ),
                ),
                (
                    "executor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="dream.benefactor",
                    ),
                ),
            ],
        ),
    ]
