# Generated by Django 4.1 on 2024-01-05 22:09

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(max_length=255)),
                ("region", models.CharField(max_length=255)),
                ("country", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.FloatField()),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("success", models.BooleanField(default=False)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Dream",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(max_length=500)),
                (
                    "dream_type",
                    models.CharField(
                        choices=[
                            ("to-have", "To-Have"),
                            ("to-meet", "To-Meet"),
                            ("to-go", "To-Go"),
                            ("to-be", "To-Be"),
                        ],
                        max_length=20,
                    ),
                ),
                ("user_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "user_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "user_type",
                    models.CharField(
                        choices=[
                            ("requestor", "Dream Requestor"),
                            ("executor", "Dream Executor"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date", models.DateField()),
                ("price", models.FloatField()),
                ("currency", models.CharField(default="USD", max_length=3)),
                (
                    "attachment",
                    models.FileField(blank=True, null=True, upload_to="attachments/"),
                ),
                ("is_activated", models.BooleanField(default=True)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="dream.location"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Benefactor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                (
                    "phone_number",
                    phone_field.models.PhoneField(
                        blank=True, help_text="Contact phone number", max_length=31
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "method_of_receipt",
                    models.CharField(
                        choices=[
                            ("personally", "Personally"),
                            ("indirectly", "Indirect"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date_execution", models.DateTimeField()),
                (
                    "dream",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="dream.dream"
                    ),
                ),
            ],
        ),
    ]
