# Generated by Django 4.1 on 2024-01-07 18:42

import django.core.validators
from django.db import migrations, models
import dream.models


class Migration(migrations.Migration):
    dependencies = [
        ("dream", "0002_payment_payer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="benefactor",
            name="date_execution",
            field=models.DateTimeField(
                validators=[dream.models.not_past_date_validator]
            ),
        ),
        migrations.AlterField(
            model_name="dream",
            name="price",
            field=models.FloatField(
                validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
    ]
