# Generated by Django 4.1 on 2024-01-07 22:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dream", "0003_alter_benefactor_date_execution_alter_dream_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="payer",
        ),
    ]
